### ISSUE TITLE
Controller question

### ISSUE THREAD

**Issue by eldair** [JustSteveKing/passwordless-auth#1]
Hi,

Sorry for creating an issue.
Is this required in controller when using `signed` middleware?

```
if (! $request->hasValidSignature()) {
    abort(Response::HTTP_UNAUTHORIZED);
}
```

**Comment by JustSteveKing** [comment]
@eldair yes you need to check the signature 😄

**Comment by eldair** [comment]
@JustSteveKing i must be missing something 🫤 isn't it already checked in signed middleware?

**Comment by JustSteveKing** [comment]
This is a good point!
